### ISSUE TITLE
html-proofer failing due to missing argument

### ISSUE THREAD

**Issue by alloydwhitlock** [CircleCI-Public/hugo-orb#25]
### Orb version

circleci/hugo@0.4.1

### What happened

After upgrading from circleci/hugo@0.3.1 to circleci/hugo@0.4.1 html-proofer has started to fail builds. There were no changes to the CircleCI `config.yml` other than a version bump. Moving the version back to circleci/hugo@0.3.1 resolves the issue. 

```
#!/bin/bash -eo pipefail
htmlproofer docs//public \
   \
   --allow-hash-href  \
   \
  --alt-ignore  \
   \
  --checks-to-ignore  \
   \
   \
   --check-html  \
   \
   \
   \
  --directory-index-file  \
   --disable-external  \
   --empty-alt-ignore  \
  --error-sort  \
   \
  --extension  \
   \
  --file-ignore  \
  --http-status-ignore  \
  --internal-domains  \
   \
   \

Traceback (most recent call last):
	4: from /usr/local/bundle/bin/htmlproofer:23:in `<main>'
	3: from /usr/local/bundle/bin/htmlproofer:23:in `load'
	2: from /usr/local/bundle/gems/html-proofer-3.13.0/bin/htmlproofer:11:in `<top (required)>'
	1: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
/usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:31:in `go': missing argument: --url-swap (OptionParser::MissingArgument)
Exited with code exit status 1

CircleCI received exit code 1

```

**This is the configuration used:**

```
version: 2.1
orbs:
  hugo: circleci/hugo@0.4.1
workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.58.3'
          source: docs/
          html-proofer: true
```

### Expected behavior

`html-proofer` should be able to run without any additional arguments.
