### ISSUE TITLE
htmlproofer 4.4.3 | Error:  invalid option: --checks-to-ignore

### ISSUE THREAD

**Issue by clementbiron** [CircleCI-Public/hugo-orb#57]
### Orb version

1.3.0

### What happened

config.yml
```yml
workflows:
  version: 2
  main:
    jobs:
      - test
      - hugo/build:
          version: '0.106'
      - deploy:
          requires:
            - test
            - hugo/build
          filters:
            branches:
              only: master
```

```console
#!/bin/bash -eo pipefail
htmlproofer ./public \
   \
   --allow-hash-href  \
   \
  --alt-ignore  \
   \
  --checks-to-ignore '' \
   \
   \
   --check-html  \
   \
   \
   \
  --directory-index-file index.html \
   --disable-external  \
   --empty-alt-ignore  \
  --error-sort ''  \
   \
  --extension '.html' \
   \
  --file-ignore '' \
  --http-status-ignore '' \
  --internal-domains '' \
   \
   \
   \
   \
   \
   \
  --log-level info \
   \
  --storage-dir 'tmp/.htmlproofer' \
  --timeframe '1h' \
  --typhoeus-config '{}' \
  --url-ignore '' \
  --url-swap ''

htmlproofer 4.4.3 | Error:  Whoops, we can't understand your command.
htmlproofer 4.4.3 | Error:  invalid option: --checks-to-ignore
Did you mean?  check-internal-hash
htmlproofer 4.4.3 | Error:  Run your command again with the --help switch to see available options.
/var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': invalid option: --checks-to-ignore (OptionParser::InvalidOption)
Did you mean?  check-internal-hash
	from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /var/lib/gems/3.0.0/gems/html-proofer-4.4.3/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/bin/htmlproofer:25:in `load'
	from /usr/local/bin/htmlproofer:25:in `<main>'

Exited with code exit status 1
```

### Expected behavior

htmlproofer runs correctly with default params.
